name: XeLaTeX auto compile

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  schedule:
    - cron: '0 3 20 * *'
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    container: kernela/texlive-gost-bac

    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX document
        working-directory: ./Src
        run: |
          latexmk -verbose -xelatex -latexoption='-halt-on-error -enable-etex -enable-installer' ./Example.tex
      
      - uses: actions/upload-artifact@v4
        with:
          name: Example.pdf
          retention-days: 30
          path: ./Src/Example.pdf
          
        

